# General Jekyll Config
#highlighter: pygments

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

url: http://cwinters.github.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, .ruby-version]

gems: [jekyll-paginate]
paginate: 50
pagination_path: blog/page:num
